### ISSUE TITLE
could you tell me where your dataset come from?

### ISSUE THREAD

**Issue by Adam3339** [panosylr/Traffic-Detector#1]
Thank you

**Comment by panosylr** [comment]
@Adam3339 

Dataset has been collected by simulating traffic (for every protocol) across University's infrastructure and networks.

**Comment by Adam3339** [comment]
> @Adam3339 
> 
> Dataset has been collected by simulating traffic (for every protocol) across University's infrastructure and networks.

how do you simulate traffic?Is there have some tools?I have trouble collecting samples.

**Comment by panosylr** [comment]
@Adam3339 
you can use common applications producing this kind of traffic (see the supported protocols in ReadMe of the project), and capture traffic through Wireshark for example. Essentially you need to create valid .pcap files and process them accordingly.

**Comment by vikrams3** [comment]
Would you be able to upload some sample pcap files to your project? So we can test it out without having to simulate the traffic?

One more question: What is the entry point to the source? There is TrafficDetector.java in at least 3 directories under src/.

**Comment by panosylr** [comment]
Hi @vikrams3 , the pcap files were collected throughout University traffic and browsing. I don't really know what could be included in there from unencrypted protocols, so I cannot share. Sorry about that.

Essentially for the main input you might need to check under: ~TrafficDetector/blob/master/src/cmd/TrafficDetector.java
Under cmd is the core functionality of the command line tool. The rest is U/I and utility classes. 

Sorry for the late response, I don't really maintain this one
